MODULES = {
    "DEEP_FRY_MODULE": {},
    "GRILLING_MODULE": {},
    "DRINKS_MODULE": {},
    "BOILER_MODULE": {},
    "STEAMING_MODULE": {},
    "TRANSPORTER_MODULE": {},
    "STIR_FRY_MODULE": {},
}
